# Generated by Django 5.1 on 2025-02-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='beers/', verbose_name='Image')),
                ('alcohol_content', models.DecimalField(decimal_places=1, max_digits=3, verbose_name="Degré d'alcool")),
                ('volume', models.IntegerField(verbose_name='Volume (cl)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bière',
                'verbose_name_plural': 'Bières',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('date', models.DateTimeField(verbose_name="Date de l'événement")),
                ('location', models.CharField(max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(blank=True, verbose_name='Lien externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date'],
            },
        ),
    ]
