# Generated by Django 5.1 on 2025-02-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('lien_info', models.URLField(blank=True, null=True, verbose_name="Lien pour plus d'informations")),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
