# Generated by Django 5.1 on 2025-02-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_evenement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='afficher_lien',
            field=models.BooleanField(default=True, verbose_name="Afficher le lien 'Plus d'informations'"),
        ),
    ]
