# Generated by Django 5.1 on 2025-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_biere_delete_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='biere',
            name='histoire',
            field=models.TextField(default='', help_text="L'histoire derrière cette bière"),
            preserve_default=False,
        ),
    ]
