# Generated by Django 5.1 on 2025-02-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_biere_histoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='biere',
            name='ibu',
            field=models.IntegerField(default=40, help_text="Indice d'amertume", verbose_name='IBU (International Bitterness Units)'),
            preserve_default=False,
        ),
    ]
