# Generated by Django 5.1 on 2025-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_biere_ibu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointDeVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'établissement")),
                ('type', models.CharField(choices=[('BAR', 'Bar'), ('CAVE', 'Cave à bières'), ('SHOP', 'Boutique'), ('AUTRE', 'Autre')], default='BAR', max_length=20)),
                ('adresse', models.CharField(max_length=200)),
                ('code_postal', models.CharField(max_length=5)),
                ('ville', models.CharField(max_length=100)),
                ('horaires', models.TextField(blank=True, help_text="Horaires d'ouverture", null=True)),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien vers le site web')),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Point de vente',
                'verbose_name_plural': 'Points de vente',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
